# Site settings
title: The Kachroo Lab
address: Concordia University, <a href="https://www.concordia.ca/research/casb.html">Center for Applied Synthetic Biology</a>
email: Email:<a aashiqh.kachroo@concordia.ca</a>
description: > # this means to ignore newlines until "baseurl:"
  Center for Applied Synthetic Biology.<br>
  The Department of Biology<br>
  Concordia University, Loyola Campus<br>
  7141 Sherbrooke St W, Montreal, QC H4B 1R6, Canada<br>
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Kachroo_Lab
github_username:  kachroolab
instagram_username: kachroolab

# Build settings
markdown: kramdown
