# Site settings
title: The Kachroo Lab
address: Concordia University, <a href="http://explore.concordia.ca/aashiq-h-kachroo">Centre for Applied Synthetic Biology</a>, <a href="http://www.concordia.ca/artsci/biology/faculty.html.html?fpid=aashiqh-kachroo"</a>Department of Biology
email: aashiq.kachroo@concordia.ca
description: > # this means to ignore newlines until "baseurl:"
  Centre for Applied Synthetic Biology<br>
  The Department of Biology<br>
  Concordia University, Loyola Campus<br>
  7141 Sherbrooke St W, Montreal, QC H4B 1R6, Canada<br>
  Room: GE 330.11 Tel: +15128482424 Ext. 2493
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Kachroo_Lab
github_username:  kachroolab
instagram_username: kachroolab

# Build settings
markdown: kramdown
